spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/greeneapp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: This is a Spring demo!
server:
  port: '8082'